name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

permissions:
  contents: write  # ✅ Allows pushing to gh-pages branch
  pages: write     # ✅ Needed for GitHub Pages deployment
  id-token: write  # ✅ Required for authentication


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ✅ Avoids auth issue

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - name: Build the app
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "Yameogo123"
          git config --global user.email "yameogoivan10@gmail.com"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token